version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgress_db
    environment:
      - POSTGRES_USER: laserhub
      - POSTGRES_PASSWORD: laser1234
      - POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data
    

  app:
    container_name: LaserApp
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="postgresql://laserhub:laser1234@localhost:5432/school"
    depends_on:
      - postgres